= Bug Tracking System

:toc:



== SQLite


. SQLite is a small, fast, self-contained, high-reliability, full-featured Database System that is available for free.
. *WE* are using SQLite because it is easy to maintain compared to mysql and ms Sql servers, SQLite also does not require a seperate server , which will be a reduntant service for the client
. SQLite is a very good choice for a small project like this, as it is very easy to use and maintain, and it is also very fast and reliable.
. It is more faster and better for network based software and deployment


== Our Entire Software does not require an internet connection

. Most of the assets and CDN used in our software are local, which means that the software will work even if the internet connection is down or if it is slow.

. This increases the reliability of the software, and also makes it more secure from hackers and other malicious attacks.

== Inbuilt Code Editor

. We have an inbuilt code editor, which is very easy to use and understand and is enitrely based on PHP language.

. The Code Editor is based mimics a real *IDE* like *Visual Studio Code*.

. It has an integrated terminal, which can be used to run commands and also to run the code.

== MD5 Hashing

. All credential data is stored in the database in the form of MD5 Hashes, which makes it more secure and also makes it harder for hackers to get the data.

. The MD5 Hashing is done using the PHP function *md5()*.

== Bug Tracking Using Kanban Board

. We have a *Kanban Board*, which is used to track the bugs and issues in the software.

. Bugs can be assigned to different departments, and the status of the bug can be changed.

. Status here means the status of the bug i.e. whether it is fixed or not.

== Inbuilt Comment System

. Other departments can comment on the bug/issue and also assign it to other departments.

. This is done because some issues require multiple departments to work on it.